### ISSUE TITLE
just want to get the paragraph information

### ISSUE THREAD

**Issue by li848689491** [nlmatics/llmsherpa#10]
The project's ability to obtain text paragraph information from PDF files is exciting. If I just want to get the paragraph information inside the PDF instead of using LLM, can I do it without requesting the API? Or can you recommend some related technologies and warehouses to me?

**Comment by ansukla** [comment]
Hi, Yes, of course you can do that. The README has examples of how to iterate through tables and paragraphs. You can also go through the chunks() function to get content of the PDF ready for LLM. Additionally, you can go through the root_node in doc and recursively through the children() to get all the descendants.

**Comment by ansukla** [comment]
Closing the Issue
