### ISSUE TITLE
Parsing bytes-like objects directly

### ISSUE THREAD

**Issue by moshewe** [nlmatics/llmsherpa#15]
Hi,

I've been experimenting with `llmsherpa` with a small `streamlit` app to which I upload PDFs, and I saw that I can't use the uploaded files (which are bytes-like) directly. 

I have code to handle that directly, though I wonder if this feature is needed by anyone else... If there's interest I can open a PR.

**Comment by ansukla** [comment]
Hi @moshewe,

That'd be a great addition! Please open a PR.

**Comment by ansukla** [comment]
Thanks for the contribution @moshewe. Closing this PR.
