### ISSUE TITLE
How to add custom parser API URL 

### ISSUE THREAD

**Issue by mohamedalani** [nlmatics/llmsherpa#23]
Looking at the documentation, to parse a pdf one has to pass a parser url which is basically an api that does all the magic (chunks, sections, paragraphs etc.). 
I was wondering where this api is hosted and if ever we can self host this api to use in a local environment. 

In the doc [here](https://llmsherpa.readthedocs.io/en/latest/llmsherpa.readers.html#llmsherpa.readers.file_reader.LayoutPDFReader) it is written the following :  _Use customer url for your private instance here_

**Comment by ansukla** [comment]
Hello @mohamedalani. We just launched private hosting option on [Azure Marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nlmaticscorp1686371242615.layout_pdf_parser?tab=Reviews). Please try this out and let us know if you have any questions.

**Comment by ansukla** [comment]
Closing the issue as it has been answered.
