### ISSUE TITLE
Can't get Demo to run with PDF file: List Index out of range

### ISSUE THREAD

**Issue by jalkestrup** [nlmatics/llmsherpa#5]
I just quickly wanted to test out the performance of this interesting approach by using the demo colab notebook, but it yields an error when loading the PDF on the very first lines... ?

![image](https://github.com/nlmatics/llmsherpa/assets/17813449/9fe8ef7c-a5ab-4e2a-b2c7-98704597b978)

**Comment by jalkestrup** [comment]
If you want to test with the specific PDF, here is the link: https://www.lederne.dk/-/media/files/ny-cvi-guides/dagpengeguide-2023.pdf

**Comment by ansukla** [comment]
@jalkestrup - This issue has been resolved. Tested your file and it looks good. Please update your version to 0.1.2 and try now.

**Comment by jalkestrup** [comment]
Thanks, it works now. And it seems very promising after a bit of testing :-) 🥳
