### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by KostyaVoronin** [nlmatics/llmsherpa#8]
When I try to load a PDF that is 541 pages long (~9.5 MB), I get the following error message:

ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

I assume it's due to the large file size? I don't have the same issue loading smaller files.

**Comment by ansukla** [comment]
This appears to be due to high server load. We are working on increasing the capacity and also offering a private hosted option soon. Please stay tuned.
